### ISSUE TITLE
Comments not supported

### ISSUE THREAD

**Issue by MarSoft** [ducent/spenx#1]
According to [docs](https://pugjs.org/language/comments.html), line starting with `//` should be rendered as a HTML comment, and line starting with `//-` should be ignored.

**Comment by MarSoft** [comment]
Also, lines starting with `<` should be treated a plain text (see the same docs page); it should help with `<!DOCTYPE>` specification.

**Comment by YuukanOO** [comment]
Hi and thanks for reporting!

As the README said, this library is not a one to one port of the pugjs library but I should have make it more clear.

That being said, comments and `<` should be added!

**Comment by YuukanOO** [comment]
Done :+1:
