### ISSUE TITLE
Jinja expressions in tag values are broken

### ISSUE THREAD

**Issue by MarSoft** [ducent/spenx#2]
I tried to add Jinja expression inside tag attribute value:
```
form(action="{{ url_for('target') }}")
```
Parser gives me this result:
`<form action="{{ url_for('target'>}}")</form>`
Somehow closing parenthesis is misplaced.
The following form works fine though:
```
form(action='{{ url_for("target") }}')
```

**Comment by YuukanOO** [comment]
That was by design, only single quotes or backticks are valid in an attribute value definition. I have updated the README.
